arena_teams:
  file: "character-arenateams.xml"
  attributes:
    name: '(doc/"arenaTeam[@teamSize=:size]").first["name"]'
    rating: '(doc/"arenaTeam[@teamSize=:size]").first["rating"].to_i'
    ranking: '(doc/"arenaTeam[@teamSize=:size]").first["ranking"].to_i'
    season_games_played: '(doc/"arenaTeam[@teamSize=:size]").first["seasonGamesPlayed"].to_i'
    season_games_won: '(doc/"arenaTeam[@teamSize=:size]").first["seasonGamesWon"].to_i'
    last_season_ranking: '(doc/"arenaTeam[@teamSize=:size]").first["lastSeasonRanking"].to_i'
    size: '(doc/"arenaTeam[@teamSize=:size]").first["size"].to_i'
    team_size: '(doc/"arenaTeam[@teamSize=:size]").first["teamSize"].to_i'
    battlegroup: '(doc/"arenaTeam[@teamSize=:size]").first["battleGroup"]'
    faction_id: '(doc/"arenaTeam[@teamSize=:size]").first["factionId"].to_i'
    faction: '(doc/"arenaTeam[@teamSize=:size]").first["faction"]'
    realm: '(doc/"arenaTeam[@teamSize=:size]").first["realm"]'
    created: '(doc/"arenaTeam[@teamSize=:size]").first["created"]'
